from classes import Color

# recreated gruvbox preview as an example
# you can use a 1d list if you want an autogenerated table - it will find the smallest rectangle to fit all elements
#   (will actually find the biggest square smaller than the amount of items then extend the width until everything fits)
#   and position the colors left-to-right top-to-bottom until it runs out
# you can also use a 2d list, such as the one in the example, to specify positions explicitly
#   each internal array is one row, starting at the top
# you can place a None anywhere in the table to leave one spot empty (transparent)
palette = [
    [
        Color('#282828', 'bg'),   Color('#cc241d', 'red'),    Color('#98971a', 'green'), Color('#d79921', 'yellow'),
        Color('#458588', 'blue'), Color('#b16286', 'purple'), Color('#689d6a', 'aqua'),  Color('#a89984', 'gray')
    ],
    [
        Color('#928374', 'gray'), Color('#fb4934', 'red'),    Color('#b8bb26', 'green'), Color('#fabd2f', 'yellow'),
        Color('#83a598', 'blue'), Color('#d3869b', 'purple'), Color('#8ec07c', 'aqua'),  Color('#ebdbb2', 'fg')
    ],
    [
        Color('#1d2021', 'bg0_h'), Color('#282828', 'bg0'), Color('#3c3836', 'bg1'),  Color('#504945', 'bg2'),
        Color('#665c54', 'bg3'),   Color('#7c6f64', 'bg4'), Color('#928374', 'gray'), Color('#d65d0e', 'orange')
    ],
    [
        None,                    Color('#32302f', 'bg0_s'), Color('#a89984', 'fg4'), Color('#bdae93', 'fg3'),
        Color('#d5c4a1', 'fg2'), Color('#ebdbb2', 'fg1'),   Color('#fbf1c7', 'fg0'), Color('#fe8019', 'orange')
    ]
]
