from typing import Literal, TypeAlias

image_format: TypeAlias = Literal[
    'png',
    'svg'
]

config_format: TypeAlias = Literal[
    'json',
    'py',
    'toml',
    'yaml'
]

# generate static list of color formats
# from colour.graph.conversion import CONVERSION_SPECIFICATIONS_DATA
# print(',\n'.join(sorted(set(f'    \'{x[0].lower()}\'' for x in CONVERSION_SPECIFICATIONS_DATA))))
#   last generated at colour-science version 0.4.6
color_format: TypeAlias = Literal[
    'cam02lcd',
    'cam02scd',
    'cam02ucs',
    'cam16 jmh',
    'cam16',
    'cam16lcd',
    'cam16scd',
    'cam16ucs',
    'cct',
    'cie 1931',
    'cie 1960 ucs',
    'cie 1976 ucs',
    'cie lab',
    'cie lchab',
    'cie lchuv',
    'cie luv uv',
    'cie luv',
    'cie ucs uv',
    'cie ucs',
    'cie uvw',
    'cie xy',
    'cie xyy',
    'cie xyz',
    'ciecam02 jmh',
    'ciecam02',
    'ciecam16 jmh',
    'ciecam16',
    'cmy',
    'cmyk',
    'css color 3',
    'din99',
    'hcl',
    'hdr-cielab',
    'hdr-cielchab',
    'hdr-ich',
    'hdr-ipt',
    'hellwig 2022 jmh',
    'hellwig 2022',
    'hexadecimal',
    'hsl',
    'hsv',
    'hunter lab',
    'hunter lchab',
    'hunter rdab',
    'hunter rdchab',
    'icacb',
    'ich ragoo 2021',
    'ich',
    'ichab',
    'ichtp',
    'ictcp',
    'igchpt',
    'igpgtg',
    'ihls',
    'ipt ragoo 2021',
    'ipt',
    'izazbz',
    'izchab',
    'jzazbz',
    'jzchab',
    'kim 2009',
    'lightness',
    'luminance',
    'mired',
    'munsell colour',
    'munsell value',
    'oklab',
    'oklch',
    'osa ucs',
    'output-referred rgb',
    'prismatic',
    'prolab',
    'prolchab',
    'rgb luminance',
    'rgb',
    'scene-referred rgb',
    'spectral distribution',
    'srgb',
    'wavelength',
    'ycbcr',
    'yccbccrc',
    'ycocg',
    'yrg',
    'zcam'
]
